name: Build Godot Project

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Download Godot
    - name: Download Godot
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_win64.exe.zip -O godot.zip
        unzip godot.zip -d godot
        chmod +x godot/Godot_v4.2.2-stable_win64.exe
        sudo mv godot/Godot_v4.2.2-stable_win64.exe /usr/local/bin/godot

    # Build the project
    - name: Export Windows build
      run: |
        mkdir -p build
        godot --export "Windows Desktop" "build/Paddle-Ball.exe"

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Paddle-Ball
        path: build/Paddle-Ball.exe
