name: Build Godot Project

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Download Godot (Linux Headless version)
    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux_headless.64.zip -O godot.zip
        unzip godot.zip -d godot
        chmod +x godot/Godot_v4.2.2-stable_linux_headless.64
        sudo mv godot/Godot_v4.2.2-stable_linux_headless.64 /usr/local/bin/godot

    # Build the project
    - name: Export Windows build
      run: |
        mkdir -p build
        godot --export "Windows Desktop" "build/Paddle-Ball.exe"

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Paddle-Ball
        path: build/Paddle-Ball.exe
