name: Build Godot Project

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Use the godot-ci action to set up Godot
    - name: Setup Godot
      uses: abarichello/godot-ci@4.2.2-stable

    # Build the project
    - name: Export Windows release build
      run: |
        mkdir -p build
        godot --export-release "Windows Desktop" "build/Paddle-Ball.exe"

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Paddle-Ball
        path: build/Paddle-Ball.exe
