name: Build Godot Project

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Godot
    - name: Set up Godot
      uses: josephbmanley/godot-action@v2.4.0
      with:
        godot-version: 3.5.1 # Change this to your Godot version

    # Build the project
    - name: Export Windows build
      run: |
        mkdir -p build
        godot --export "Windows Desktop" "build/Paddle-Ball.exe"

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Paddle-Ball
        path: build/Paddle-Ball.exe
